// src/graphics/16x9-1p/main.vue
<template>
    <div id="container">
        <img id="Background" src="../img/layouts/widescreen_1.png" />

        <div v-if="activeRun" id="runners">
            <template v-if="activeRun.teams" v-for="team in activeRun.teams">
                <template v-for="player in team.players">
                    <player
                        :key="player.id"
                        class="Player"
                        :cycle="nameCycle"
                        :player="player"
                    />
                </template>
            </template>
            <commentator-list
                :commentators="commentators"
                v-if="numRunners < 3 && commentators.amount > 0"
                id="commentators"
            />
            <reader-name
                :reader="reader"
                v-if="numRunners < 4 && reader"
                id="reader"
            />
        </div>
        <run-info
            id="RunInfo"
            v-if="activeRun"
            :run="activeRun"
            :maxTitleSize="36"
        />
        <timer-view id="timer" />
        <sponsors-view id="sponsors" :sponsors="sponsors" />
    </div>
</template>

<script lang="ts">
    import { Vue, Component } from 'vue-property-decorator';
    import type { RunDataActiveRun } from 'nodecg/bundles/nodecg-speedcontrol/src/types/schemas';
    import type {
        NameCycle,
        Commentators,
        Reader,
    } from '@gsps-layouts/types/schemas';
    import type { Asset } from '@gsps-layouts/types';
    import { Getter } from 'vuex-class';
    import TimerView from '../_misc/components/Timer.vue';
    import RunInfo from '../_misc/components/RunInfo.vue';
    import Player from '../_misc/components/Player.vue';
    import CommentatorList from '../_misc/components/Commentator.vue';
    import ReaderName from '../_misc/components/Reader.vue';
    import SponsorsView from '../_misc/components/Sponsors.vue';

    @Component({
        components: {
            TimerView,
            RunInfo,
            Player,
            CommentatorList,
            ReaderName,
            SponsorsView,
        },
    })
    export default class extends Vue {
        @Getter readonly activeRun!: RunDataActiveRun;
        @Getter readonly nameCycle!: NameCycle;
        @Getter readonly commentators!: Commentators;
        @Getter readonly reader!: Reader;
        @Getter readonly sponsors!: Asset[];
        data() {
            return {
                numRunners: 0,
            };
        }

        mounted() {
            this.activeRun!.teams.forEach((team: any) => {
                this.$data.numRunners += team.players.length;
            });

            this.$watch(
                function () {
                    return this.activeRun;
                },
                function () {
                    this.$data.numRunners = 0;
                    this.activeRun!.teams.forEach((team: any) => {
                        this.$data.numRunners += team.players.length;
                    });
                }
            );
        }
    }
</script>

<style>
    @import url('../css/styles.css');

    #container {
        text-align: center;
    }

    #Background {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        z-index: -1;
    }

    #timer {
        position: absolute;
        right: 56px;
        bottom: 16px;
        height: 153.6px;
        width: 576px;
        font-size: 92px;
    }

    #bottomLeft {
        display: flex;
        flex-direction: column;
        position: absolute;
        top: 583px;
        width: 578px;
        height: 430px;
    }

    html {
        display: block;
        width: 1920px;
        height: 1014px;
    }

    #RunInfo {
        left: 468px;
        bottom: -10px;
        width: 780px;
        height: 156px;
        position: absolute;
    }

    #runners {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        position: relative;
        padding-left: 11px;
        width: 437px;
    }

    .Player {
        position: relative;
        left: -11px;
        top: 487px;
        margin-bottom: 0px;
        font-size: 28.8px;
        width: 437px;
    }

    #commentators {
        position: relative;
        top: 487px;
        margin-bottom: 0px;
        font-size: 20px;
        width: 437px;
        left: -11px;
    }

    #reader {
        position: relative;
        top: 487px;
        margin-bottom: 9px;
        font-size: 20px;
        width: 437px;
        left: -11px;
    }

    #sponsors {
        position: absolute;
        bottom: 30px;
        left: 25px;
        width: 400px;
        height: 341px;
        /* background-color: aqua; */
    }
</style>

// src/browser/graphics/16x9-1p.tsx
import { render } from '../render';
import layoutBg from './img/layouts/16x9-1p.png';
import styled from 'styled-components';
import './css/style.css';
import RunInfo from './components/run-info';
import { Timer as TimerEl } from './components/timer';
import MediaBox from './components/media-box';
import Nameplate from './components/nameplate';
import Reader from './components/reader';
import Commentators from './components/commentators';
import { useReplicant } from 'use-nodecg';
import { RunDataActiveRun } from '../../../../nodecg-speedcontrol/src/types/schemas';

const LayoutContainer = styled.div`
  width: 1920px;
  height: 1030px;
  background-image: url(${layoutBg});
  margin: 0;
  padding: 0;
`;

const LeftSide = styled.div`
  position: fixed;
  width: 477px;
  height: 587px;
  top: 439px;
  left: 0px;
  display: flex;
  flex-direction: column;
  text-align: center;
`;

const BottomRight = styled.div`
  position: fixed;
  width: 1439px;
  height: 213px;
  left: 481px;
  top: 813px;
  text-align: center;
  display: grid;
  grid-template-columns: 1fr 0.5fr;
  grid-template-rows: 1fr;
  grid-column-gap: 0px;
  grid-row-gap: 0px;
  align-items: center;
  justify-content: center;
`;

const Run = styled(RunInfo)`
  grid-area: 1 / 1 / 2 / 2;
`;

const Timer = styled(TimerEl)`
  grid-area: 1 / 2 / 2 / 3;
`;

export const App = () => {
  const [activeRun] = useReplicant<RunDataActiveRun | undefined>('runDataActiveRun', undefined, {
    namespace: 'nodecg-speedcontrol',
  });

  return (
    <LayoutContainer>
      <LeftSide>
        {activeRun && (
          <>
            {activeRun.teams.map((team) => {
              return (
                <>
                  {team.players.map((player) => {
                    return <Nameplate key={player.name} player={player} />;
                  })}
                </>
              );
            })}
          </>
        )}
        <Commentators />
        <Reader />
        <MediaBox />
      </LeftSide>
      <BottomRight>
        <Run fontSize={56} />
        <Timer fontSize={72} />
      </BottomRight>
    </LayoutContainer>
  );
};

render(<App />);
