// src/graphics/4x3-2p/main.vue
<template>
  <div id="container">
    <img id="Background" src="../img/layouts/standard_2.png" />

    <div v-if="activeRun" id="runners">
      <div v-if="activeRun.teams[0]" id="team1">
        <template v-for="player in activeRun.teams[0].players">
          <player
            :key="player.id"
            class="Player"
            :cycle="nameCycle"
            :player="player"
          />
        </template>
        <transition name="fade">
          <finish-time
            v-if="
              timer.teamFinishTimes[activeRun.teams[0].id] &&
              timer.teamFinishTimes[activeRun.teams[0].id].state === 'completed'
            "
            :style="{ left: '655px', position: 'absolute' }"
            :side="'left'"
            :place="team1Placement"
            :time="timer.teamFinishTimes[activeRun.teams[0].id].time"
          />
        </transition>

        <commentator-list
          :commentators="commentators"
          v-if="
            activeRun.teams[0].players.length < 2 && commentators.amount > 0
          "
          id="commentators"
        />
      </div>
      <div v-if="activeRun.teams[1]" id="team2">
        <template v-for="player in activeRun.teams[1].players">
          <player
            :key="player.id"
            class="Player"
            :cycle="nameCycle"
            :player="player"
          />
        </template>
        <transition name="fade">
          <finish-time
            v-if="
              timer.teamFinishTimes[activeRun.teams[1].id] &&
              timer.teamFinishTimes[activeRun.teams[1].id].state === 'completed'
            "
            :style="{ right: '824px', position: 'absolute' }"
            :side="'right'"
            :place="team2Placement"
            :time="timer.teamFinishTimes[activeRun.teams[1].id].time"
          />
        </transition>

        <reader-name
          :reader="reader"
          v-if="activeRun.teams[1].players.length < 2 && reader"
          id="reader"
        />
      </div>
    </div>
    <run-info
      id="RunInfo"
      v-if="activeRun"
      :run="activeRun"
      :maxTitleSize="43"
    />
    <timer-view id="timer" />
    <sponsors-view id="sponsors" :sponsors="sponsors" />
  </div>
</template>

<script lang="ts">
  import { Vue, Component } from 'vue-property-decorator';
  import type {
    RunDataActiveRun,
    Timer,
  } from 'nodecg/bundles/nodecg-speedcontrol/src/types/schemas';
  import type {
    NameCycle,
    Commentators,
    Reader,
  } from '@gsps-layouts/types/schemas';
  import type { Asset } from '@gsps-layouts/types';
  import { Getter } from 'vuex-class';
  import TimerView from '../_misc/components/Timer.vue';
  import RunInfo from '../_misc/components/RunInfo.vue';
  import Player from '../_misc/components/Player.vue';
  import CommentatorList from '../_misc/components/Commentator.vue';
  import ReaderName from '../_misc/components/Reader.vue';
  import SponsorsView from '../_misc/components/Sponsors.vue';
  import FinishTime from '../_misc/components/FinishTime.vue';

  @Component({
    components: {
      TimerView,
      RunInfo,
      Player,
      CommentatorList,
      ReaderName,
      SponsorsView,
      FinishTime,
    },
  })
  export default class extends Vue {
    @Getter readonly activeRun!: RunDataActiveRun;
    @Getter readonly nameCycle!: NameCycle;
    @Getter readonly commentators!: Commentators;
    @Getter readonly reader!: Reader;
    @Getter readonly sponsors!: Asset[];
    @Getter readonly timer!: Timer;
    data() {
      return {
        numRunners: 0,
      };
    }

    get team1Placement() {
      let place = 1;
      if (this.placements.length > 0) {
        this.placements.forEach((placement) => {
          if (placement.object[0] === this.activeRun.teams[0].id) {
            place = placement.place;
          }
        });
      }
      return place;
    }

    get team2Placement() {
      let place = 1;
      if (this.placements.length > 0) {
        this.placements.forEach((placement) => {
          if (placement.object[0] === this.activeRun.teams[1].id) {
            place = placement.place;
          }
        });
      }
      return place;
    }

    get placements() {
      return Object.entries(this.timer.teamFinishTimes)
        .sort(([, a], [, b]) => a.milliseconds - b.milliseconds)
        .map((p, i) => ({ object: p, place: i + 1 }));
    }

    mounted() {
      this.activeRun!.teams.forEach((team: any) => {
        this.$data.numRunners += team.players.length;
      });

      this.$watch(
        function () {
          return this.activeRun;
        },
        function () {
          this.$data.numRunners = 0;
          this.activeRun!.teams.forEach((team: any) => {
            this.$data.numRunners += team.players.length;
          });
        }
      );
    }
  }
</script>

<style>
  @import url('../css/styles.css');

  #container {
    text-align: center;
  }

  #Background {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    z-index: -1;
  }

  #timer {
    left: 686.4px;
    bottom: 15px;
    height: 78px;
    width: 547.2px;
    font-size: 67.2px;
    z-index: 2;
    position: absolute;
  }

  #bottomLeft {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 583px;
    width: 578px;
    height: 430px;
  }

  html {
    display: block;
    width: 1920px;
    height: 1014px;
  }

  #RunInfo {
    position: absolute;
    bottom: 35px;
    width: 634.8px;
    height: 160px;
  }

  #runners {
    top: 720px;
    width: 100%;
    font-size: 28.8px;
    left: -11px;
    position: absolute;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }

  .Player {
    position: relative;
    margin-bottom: 0px;
    width: 640px;
  }

  #team1 {
    right: 1280px;
    align-self: flex-start;
    display: flex;
    flex-direction: column;
  }

  #team2 {
    left: 1280px;
    align-self: flex-start;
    display: flex;
    flex-direction: column;
  }

  #commentators {
    position: relative;
    margin-bottom: 0px;
    width: 640px;
  }

  #reader {
    position: relative;
    margin-bottom: 0px;
    width: 640px;
  }

  #sponsors {
    position: absolute;
    bottom: 24px;
    right: 0px;
    width: 640px;
    height: 180px;
    /* 		background-color: aqua; */
  }

  .fade-enter-active,
  .fade-leave-active {
    transition: opacity 0.2s;
  }
  .fade-enter,
  .fade-leave-to {
    opacity: 0;
  }
</style>

// src/browser/graphics/4x3-2p.tsx
import { render } from '../render';
import layoutBg from './img/layouts/4x3-2p.png';
import layoutBgWithDonationBar from './img/layouts/4x3-2p-donationbar.png';
import styled from 'styled-components';
import RunInfo from './components/run-info';
import Timer from './components/timer';
import MediaBox from './components/media-box';
import Nameplate from './components/nameplate';
import Reader from './components/reader';
import Commentators from './components/commentators';
import { useReplicant } from 'use-nodecg';
import {
  RunDataActiveRun,
  Timer as TimerType,
} from 'speedcontrol/src/types/schemas';
import { Fragment, useEffect, useState } from 'react';
import ThemeProvider from './components/theme-provider';
import DonationBar from './components/donation-bar';
import FinishTime from './components/finish-time';

const LayoutContainer = styled.div<{ showDonationBar: boolean }>`
  width: 1920px;
  height: 1030px;
  background-image: url(${(props) => (props.showDonationBar ? layoutBgWithDonationBar : layoutBg)});
  margin: 0;
  padding: 0;
  text-align: center;
`;

const BottomLeft = styled.div<{ showDonationBar: boolean }>`
  display: flex;
  flex-direction: column;
  position: fixed;
  left: 0px;
  top: 722px;
  width: 679px;
  height: ${(props) => (props.showDonationBar ? '256px' : '294px')};
  justify-content: space-between;
`;

const BottomRight = styled.div<{ showDonationBar: boolean }>`
  display: flex;
  flex-direction: column;
  position: fixed;
  left: 1242px;
  top: 722px;
  width: 678px;
  height: ${(props) => (props.showDonationBar ? '264px' : '304px')};
`;

const Names = styled.div`
  display: flex;
  flex-direction: column;
  gap: 0px;
`;

const Donations = styled.div`
  position: fixed;
  width: 1920px;
  height: 44px;
  bottom: 0px;
`;

const Team1FinishTime = styled.div`
  position: fixed;
  top: 722px;
  left: 679px;
`;

const Team2FinishTime = styled.div`
  position: fixed;
  top: 722px;
  right: 679px;
`;

export const App = () => {
  const [activeRun] = useReplicant<RunDataActiveRun | undefined>('runDataActiveRun', undefined, {
    namespace: 'nodecg-speedcontrol',
  });
  const [showDonationBar] = useReplicant<boolean>('showDonationBar', true);
  const [timer] = useReplicant<TimerType | undefined>('timer', undefined, {
    namespace: 'nodecg-speedcontrol',
  });
  const [placements, setPlacements] = useState<
    {
      place: number;
      placementData: [
        string,
        {
          time: string;
          state: 'forfeit' | 'completed';
          milliseconds: number;
          timestamp: number;
        }
      ];
    }[]
  >([]);

  function team1Placement() {
    let place = 1;
    if (placements.length > 0) {
      placements.forEach((placement) => {
        if (placement.placementData[0] === activeRun!.teams[0]!.id) {
          place = placement.place;
        }
      });
    }
    return place;
  }

  function team2Placement() {
    let place = 1;
    if (placements.length > 0) {
      placements.forEach((placement) => {
        if (placement.placementData[0] === activeRun!.teams[1]!.id) {
          place = placement.place;
        }
      });
    }
    return place;
  }

  useEffect(() => {
    if (typeof timer === 'undefined') return;

    setPlacements(
      Object.entries(timer.teamFinishTimes)
        .sort(([, a], [, b]) => a.milliseconds - b.milliseconds)
        .map((p, i) => ({ place: i + 1, placementData: p }))
    );
  }, [timer]);

  return (
    <ThemeProvider>
      <LayoutContainer showDonationBar={showDonationBar}>
        <BottomLeft showDonationBar={showDonationBar}>
          <Names>
            {activeRun && (
              <>
                {activeRun.teams[0] && (
                  <>
                    {activeRun.teams.length === 1 ? (
                      <>
                        {activeRun.teams.map((team) => {
                          return (
                            <Fragment key={team.id}>
                              {team.players.map((player, index) => {
                                if (index % 2 == 0) {
                                  return <Nameplate key={player.name} player={player} />;
                                } else {
                                  return <></>;
                                }
                              })}
                            </Fragment>
                          );
                        })}
                        {activeRun.teams[0].players.length < 5 && <Commentators />}
                      </>
                    ) : (
                      <>
                        {activeRun.teams[0].players.map((player) => {
                          return (
                            <Fragment key={player.id}>
                              <Nameplate key={player.name} player={player} />
                            </Fragment>
                          );
                        })}
                        {activeRun.teams[0].players.length < 5 && <Commentators />}
                      </>
                    )}
                  </>
                )}
              </>
            )}
          </Names>

          <RunInfo fontSize={44} />
          <Timer fontSize={56} />
        </BottomLeft>
        <BottomRight showDonationBar={showDonationBar}>
          <Names>
            {activeRun && (
              <>
                {activeRun.teams[1] ? (
                  <>
                    {activeRun.teams[1].players.map((player) => {
                      return (
                        <Fragment key={player.id}>
                          <Nameplate key={player.name} player={player} />
                        </Fragment>
                      );
                    })}
                  </>
                ) : (
                  <>
                    <>
                      {activeRun.teams.map((team) => {
                        return (
                          <Fragment key={team.id}>
                            {team.players.map((player, index) => {
                              if (index % 2 != 0) {
                                return <Nameplate key={player.name} player={player} />;
                              } else {
                                return <></>;
                              }
                            })}
                          </Fragment>
                        );
                      })}
                    </>
                  </>
                )}
              </>
            )}
            <Reader />
          </Names>

          <MediaBox />
        </BottomRight>
        {activeRun &&
          timer &&
          activeRun.teams[0] &&
          activeRun.teams.length > 1 &&
          timer.teamFinishTimes[activeRun.teams[0].id] != undefined &&
          timer.teamFinishTimes[activeRun.teams[0].id]!.state === 'completed' && (
            <Team1FinishTime>
              <FinishTime
                side="left"
                place={team1Placement()}
                time={timer.teamFinishTimes[activeRun.teams[0].id]!.time}
              />
            </Team1FinishTime>
          )}
        {activeRun &&
          timer &&
          activeRun.teams[1] &&
          timer.teamFinishTimes[activeRun.teams[1].id] != undefined &&
          timer.teamFinishTimes[activeRun.teams[1].id]!.state === 'completed' && (
            <Team2FinishTime>
              <FinishTime
                side="right"
                place={team2Placement()}
                time={timer.teamFinishTimes[activeRun.teams[1].id]!.time}
              />
            </Team2FinishTime>
          )}
        {showDonationBar && (
          <Donations>
            <DonationBar />
          </Donations>
        )}
      </LayoutContainer>
    </ThemeProvider>
  );
};

render(<App />);
