// src/graphics/ds-1p/main.vue
<template>
  <div id="container">
    <img id="Background" src="../img/layouts/ds_1.png" />

    <div v-if="activeRun" id="runners">
      <template v-if="activeRun.teams" v-for="team in activeRun.teams">
        <template v-for="player in team.players">
          <player
            :key="player.id"
            class="Player"
            :cycle="nameCycle"
            :player="player"
          />
        </template>
      </template>
      <commentator-list
        v-if="numRunners < 3 && commentators.amount > 0"
        id="commentators"
      />
      <reader-name v-if="numRunners < 4 && reader" id="reader" />
    </div>
    <run-info id="RunInfo" v-if="activeRun" :maxTitleSize="36" />
    <timer-view id="timer" />
    <sponsors id="sponsors" />
  </div>
</template>

<script lang="ts">
  import { Vue, Component } from 'vue-property-decorator';
  import type { RunDataActiveRun } from 'speedcontrol/src/types/schemas';
  import type {
    NameCycle,
    Commentators,
    Reader,
  } from '@gsps-layouts/types/schemas';
  import type { Asset, LogoCycle } from '@gsps-layouts/types';
  import { Getter } from 'vuex-class';
  import TimerView from '../_misc/components/Timer.vue';
  import RunInfo from '../_misc/components/RunInfo.vue';
  import Player from '../_misc/components/Player.vue';
  import CommentatorList from '../_misc/components/Commentator.vue';
  import ReaderName from '../_misc/components/Reader.vue';
  import Sponsors from '../_misc/components/Sponsors.vue';

  @Component({
    components: {
      TimerView,
      RunInfo,
      Player,
      CommentatorList,
      ReaderName,
      Sponsors,
    },
  })
  export default class extends Vue {
    @Getter readonly activeRun!: RunDataActiveRun;
    @Getter readonly nameCycle!: NameCycle;
    @Getter readonly commentators!: Commentators;
    @Getter readonly reader!: Reader;
    @Getter readonly sponsors!: Asset[];
    @Getter readonly logoCycles!: LogoCycle[];
    data() {
      return {
        numRunners: 0,
      };
    }

    mounted() {
      this.activeRun!.teams.forEach((team: any) => {
        this.$data.numRunners += team.players.length;
      });

      this.$watch(
        function () {
          return this.activeRun;
        },
        function () {
          this.$data.numRunners = 0;
          this.activeRun!.teams.forEach((team: any) => {
            this.$data.numRunners += team.players.length;
          });
        }
      );
    }
  }
</script>

<style>
  @import url('../css/styles.css');

  #container {
    text-align: center;
  }

  #Background {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    z-index: -1;
  }

  #timer {
    position: absolute;
    right: 6px;
    bottom: 16px;
    height: 153.6px;
    width: 506px;
    font-size: 92px;
  }

  #bottomLeft {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 583px;
    width: 578px;
    height: 430px;
  }

  html {
    display: block;
    width: 1920px;
    height: 1014px;
  }

  #RunInfo {
    left: 908px;
    bottom: -10px;
    width: 500px;
    height: 156px;
    position: absolute;
    /* background-color: aqua; */
  }

  #runners {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    position: relative;
    padding-left: 11px;
    width: 806px;
  }

  .Player {
    position: relative;
    left: -11px;
    top: 487px;
    margin-bottom: 0px;
    font-size: 28.8px;
    width: 806px;
  }

  #commentators {
    position: relative;
    top: 487px;
    margin-bottom: 0px;
    font-size: 20px;
    width: 437px;
    left: -11px;
  }

  #reader {
    position: relative;
    top: 487px;
    margin-bottom: 9px;
    font-size: 20px;
    width: 437px;
    left: -11px;
  }

  #sponsors {
    position: absolute;
    bottom: 10px;
    left: 10px;
    width: 355px;
    height: 341px;
    /* background-color: aqua; */
  }
</style>

// src/browser/graphics/ds-1p.tsx
import { render } from '../render';
import layoutBg from './img/layouts/4x3-2p.png';
import layoutBgWithDonationBar from './img/layouts/4x3-2p-donationbar.png';
import styled from 'styled-components';
import RunInfo from './components/run-info';
import Timer from './components/timer';
import MediaBox from './components/media-box';
import Nameplate from './components/nameplate';
import Reader from './components/reader';
import Commentators from './components/commentators';
import { useReplicant } from 'use-nodecg';
import {
  RunDataActiveRun,
} from 'speedcontrol/src/types/schemas';
import { Fragment } from 'react';
import ThemeProvider from './components/theme-provider';
import DonationBar from './components/donation-bar';
import { RunDataPlayer, RunDataTeam } from 'speedcontrol/src/types';

const LayoutContainer = styled.div<{ showDonationBar: boolean }>`
  width: 1920px;
  height: 1030px;
  background-image: url(${(props) => (props.showDonationBar ? layoutBgWithDonationBar : layoutBg)});
  margin: 0;
  padding: 0;
  text-align: center;
`;

const BottomLeft = styled.div<{ showDonationBar: boolean }>`
  display: flex;
  flex-direction: column;
  position: fixed;
  left: 0px;
  top: 722px;
  width: 679px;
  height: ${(props) => (props.showDonationBar ? '256px' : '294px')};
  justify-content: space-between;
`;

const BottomRight = styled.div<{ showDonationBar: boolean }>`
  display: flex;
  flex-direction: column;
  position: fixed;
  left: 1242px;
  top: 722px;
  width: 678px;
  height: ${(props) => (props.showDonationBar ? '264px' : '304px')};
`;

const Names = styled.div`
  display: flex;
  flex-direction: column;
  gap: 0px;
`;

const Donations = styled.div`
  position: fixed;
  width: 1920px;
  height: 44px;
  bottom: 0px;
`;

export const App = () => {
  const [activeRun] = useReplicant<RunDataActiveRun | undefined>('runDataActiveRun', undefined, {
    namespace: 'nodecg-speedcontrol',
  });
  const [showDonationBar] = useReplicant<boolean>('showDonationBar', true);

  const getCurrentRelayRunner = (team: RunDataTeam) => {
    let currentRelayRunner: RunDataPlayer | undefined;

    team.players.forEach((player: RunDataPlayer) => {
      if (player.id === team.relayPlayerID) {
        currentRelayRunner = player;
      }
    });
    return currentRelayRunner;
  };

  return (
    <ThemeProvider>
      <LayoutContainer showDonationBar={showDonationBar}>
        <BottomLeft showDonationBar={showDonationBar}>
          <Names>
            {(() => {
              if (activeRun) {
                if (activeRun.relay) {
                  if (activeRun.teams[0]) {
                    const currentRelayRunner = getCurrentRelayRunner(activeRun.teams[0]);
                    if (currentRelayRunner != undefined) {
                      return (
                        <>
                          <Nameplate player={currentRelayRunner} />
                        </>
                      );
                    } else {
                      return <></>;
                    }
                  } else {
                    return <></>;
                  }
                } else {
                  return (
                    <>
                      {activeRun.teams.map((team) => {
                        return (
                          <Fragment key={team.id}>
                            {team.players.map((player) => {
                              return <Nameplate key={player.name} player={player} />;
                            })}
                          </Fragment>
                        );
                      })}
                    </>
                  );
                }
              } else {
                return <></>;
              }
            })()}
            <Commentators />
            <Reader />
          </Names>

          <RunInfo fontSize={40} />
          <Timer fontSize={56} />
        </BottomLeft>
        <BottomRight showDonationBar={showDonationBar}>
          <MediaBox />
        </BottomRight>
        {showDonationBar && (
          <Donations>
            <DonationBar />
          </Donations>
        )}
      </LayoutContainer>
    </ThemeProvider>
  );
};

render(<App />);
