// src/graphics/video/main.vue
<template>
  <div id="container">
    <img id="Background" src="../img/layouts/video_bg-min.png" />

    <div id="nextRunInfo">
      <div id="nextRunLabel"><b>NADCHODZĄCY RUN</b></div>
      <video-next-run v-if="activeRun" :run="activeRun" />
    </div>
  </div>
</template>

<script lang="ts">
  import { Vue, Component } from 'vue-property-decorator';
  import type { RunDataActiveRun } from 'nodecg/bundles/nodecg-speedcontrol/src/types/schemas';
  import { Getter } from 'vuex-class';
  import VideoNextRun from './components/NextRun.vue';

  @Component({
    components: {
      VideoNextRun,
    },
  })
  export default class extends Vue {
    @Getter readonly activeRun!: RunDataActiveRun;
  }
</script>

<style>
  @import url('../css/styles.css');

  #container {
    text-align: center;
  }

  #Background {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    z-index: -1;
  }

  #nextRunInfo {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 866px;
    left: 208px;
    width: 1502px;
    height: 100px;
    /* background-color: blue; */
  }

  #nextRunLabel {
    text-align: center;
    color: white;
    font-size: 24px;
    margin-bottom: 10px;
  }

  html {
    display: block;
    width: 1920px;
    height: 1014px;
  }
</style>

// src/browser/graphics/video.tsx
import styled from 'styled-components';
import './css/style.css';
import mainBg from './img/layouts/video.png';
import { render } from '../render';
import { useReplicant } from 'use-nodecg';
import { RunDataActiveRun } from '../../../../nodecg-speedcontrol/src/types/schemas';
import { formatPlayers } from '../format-players';

const LayoutContainer = styled.div`
  width: 1920px;
  height: 1030px;
  background-image: url(${mainBg});
  margin: 0;
  padding: 0;
`;

const App = () => {
  return (
    <LayoutContainer>
      <NextRun />
    </LayoutContainer>
  );
};

const NextRunComponentContainer = styled.div`
  display: flex;
  flex-direction: column;
  position: absolute;
  top: 866px;
  left: 208px;
  width: 1502px;
  height: 100px;
`;

const NextRunLabel = styled.div`
  text-align: center;
  color: white;
  font-size: 24px;
  margin-bottom: 10px;
`;

const NextRunContainer = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  color: white;
  font-size: 30px;
`;

const NextRunDetails = styled.span`
  font-weight: 500;
  display: flex;
  flex-direction: row;
  gap: 10px;
`;

const NextRun = () => {
  const [currentRun] = useReplicant<RunDataActiveRun | undefined>('runDataActiveRun', undefined, {
    namespace: 'nodecg-speedcontrol',
  });

  return (
    <>
      {currentRun && (
        <NextRunComponentContainer>
          <NextRunLabel>NADCHODZĄCY RUN</NextRunLabel>
          <NextRunContainer className="shadow">
            {currentRun.game && <span>{currentRun.game}</span>}
            <NextRunDetails>
              {currentRun.category && <span>{currentRun.category} /</span>}
              {currentRun.estimate && <span>EST: {currentRun.estimate} /</span>}
              {currentRun.system && <span>{currentRun.system} /</span>}
              {currentRun.teams.length > 0 && <span>{formatPlayers(currentRun)}</span>}
            </NextRunDetails>
          </NextRunContainer>
        </NextRunComponentContainer>
      )}
    </>
  );
};

render(<App />);
