// src/graphics/omnibar/components/Total.vue
<template>
  <div id="total">
    <span id="totalAmount"></span>
    <div id="totalCurrency" style="font-size: 60%">PLN</div>
  </div>
</template>

<script lang="ts">
  import type { Total } from '../../../types/schemas';
  import gsap from 'gsap';
  import { Component, Vue } from 'vue-property-decorator';

  const totalRep = nodecg.Replicant<Total>('total');

  @Component
  export default class OmnibarTotal extends Vue {
    data() {
      return {
        total: { raw: 0 },
      };
    }

    mounted() {
      const updateHandler = () => {
        document.getElementById('totalAmount')!.innerHTML =
          this.$data.total.raw.toLocaleString('en-US', {
            maximumFractionDigits: 0,
            minimumFractionDigits: 0,
          });
      };
      totalRep.on('change', (newVal) => {
        gsap.to(this.$data.total, {
          duration: 3,
          raw: newVal.raw,
          roundProps: 'raw',
          onUpdate: updateHandler,
          ease: 'power4',
        });
      });
    }
  }
</script>

<style scoped>
  #total {
    color: white;
    background-color: #3a008b;
    font-size: 32px;
    position: relative;
    height: 100%;
    white-space: nowrap;
    padding-right: 9.6px;
    -ms-flex: none;
    -webkit-flex: none;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    display: flex;
    flex: none;
  }

  #totalAmount {
    display: block;
    font-weight: 600;
    margin-left: 6px;
    margin-right: 8px;
  }
</style>

// src/browser/graphics/components/przerwa/total.tsx
import styled from 'styled-components';
import { useEffect, useState } from 'react';
import { Total as TotalType } from 'src/types/generated';
import gsap from 'gsap';

const AmountDiv = styled.div`
  font-size: 96px;
  align-self: flex-end;
  padding-left: 10px;
  padding-right: 10px;
  margin-top: auto;
  margin-bottom: auto;
  text-align: center;
  font-variant-numeric: tabular-nums;
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 10px;
  position: fixed;
  top: 150px;
  right: 120px; 
`;

const Currency = styled.div`
  font-size: 0.5em;
`;

export const Total = () => {
  const totalRep = nodecg.Replicant<TotalType>('total');
  const [amount, setAmount] = useState({ raw: 0, formatted: '0' });
  const localAmount = { raw: 0 };

  useEffect(() => {
    const ctx = gsap.context(() => {
      totalRep.on('change', (newVal) => {
        if (typeof newVal != 'undefined') {
          gsap.to(localAmount, {
            duration: 5,
            raw: newVal.raw,
            roundProps: 'raw',
            ease: 'power4',
            onUpdate: () => {
              setAmount({
                raw: localAmount.raw,
                formatted: localAmount.raw.toLocaleString('en-US', {
                  maximumFractionDigits: 0,
                  minimumFractionDigits: 0,
                }),
              });
            },
          });
        }
      });
    });

    return () => ctx.revert();
  }, []);

  return (
    <AmountDiv className='shadow'>
      {amount.formatted}
      <Currency>PLN</Currency>
    </AmountDiv>
  );
};

export default Total;
