// src/browser/dashboard/highlight.tsx
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { render } from '../render';
import { Button, Stack } from '@mui/material';

const App = () => {
  return (
    <DashboardThemeProvider>
      <Stack>
        <Button
          variant="contained"
          onClick={() => {
            nodecg.sendMessage('makeHighlight');
          }}>
          Zrób highlight ręcznie
        </Button>
      </Stack>
    </DashboardThemeProvider>
  );
};

render(<App />);

// src/dashboard/highlight/main.vue
<template>
  <v-app>
    <v-btn @click="makeHighlight">Zrób highlight ręcznie</v-btn>
  </v-app>
</template>

<script lang="ts">
  import { Vue, Component } from 'vue-property-decorator';

  @Component
  export default class extends Vue {
    data() {
      return {
        amount: 0,
      };
    }

    makeHighlight(): void {
      nodecg.sendMessage('makeHighlight');
    }
  }
</script>

<style>
  body {
    text-align: center;
  }
</style>
