// src/browser/graphics/components/finish-time.tsx
import styled from 'styled-components';

const FinishTimeContainer = styled.div<{ side: 'left' | 'right' }>`
  width: 150px;
  background-color: #5f3ac2;
  height: 30px;
  display: flex;
  flex-direction: ${(props) => (props.side == 'right' ? 'row-reverse' : 'row')};
`;

const TimeDiv = styled.div`
  font-size: 24px;
  flex: 1;
  height: 100%;
`;

const PlaceDiv = styled.div`
  background-color: #ffbd16;
  color: #35216b;
  font-size: 25px;
  min-width: 25px;
`;

const FinishTime = ({
  time,
  place,
  side,
}: {
  time: string;
  place: number;
  side: 'left' | 'right';
}) => {
  return (
    <FinishTimeContainer side={side}>
      <TimeDiv>
        <p style={{ margin: 'auto' }}>{time}</p>
      </TimeDiv>
      <PlaceDiv>{place}</PlaceDiv>
    </FinishTimeContainer>
  );
};

export default FinishTime;

// src/graphics/_misc/components/FinishTime.vue
<template>
  <span>
    <template v-if="side === 'right'">
      <div class="finish">
        <div
          id="placement-background"
          :style="{
            width: '20%',
            position: 'absolute',
            'background-color': '#ffbd16',
            height: '100%',
          }"
        ></div>
        <span
          :style="{
            width: '80%',
            float: 'right',
            'margin-top': '-3px',
            'z-index': '3',
          }"
          ><b>{{ time }}</b></span
        >
        <span
          :style="{
            width: '20%',
            right: '144px',
            height: '100%',
            color: 'black',
            'margin-top': '-4px',
            'z-index': '3',
            position: 'absolute',
          }"
        >
          {{ place }}
        </span>
      </div>
    </template>
    <template v-else-if="side === 'left'">
      <div class="finish">
        <div
          id="placement-background"
          :style="{
            width: '20%',
            position: 'absolute',
            'background-color': '#ffbd16',
            height: '100%',
            left: '144px',
          }"
        ></div>
        <span
          :style="{
            width: '80%',
            float: 'left',
            'margin-top': '-3px',
            'z-index': '3',
          }"
          ><b>{{ time }}</b></span
        >
        <span
          :style="{
            width: '20%',
            left: '144px',
            height: '100%',
            color: 'black',
            'margin-top': '-4px',
            'z-index': '3',
            position: 'absolute',
          }"
        >
          {{ place }}
        </span>
      </div>
    </template>
  </span>
</template>

<script>
  export default {
    name: 'FinishTime',
    props: ['time', 'place', 'side'],
  };
</script>

<style scoped>
  .finish {
    width: 180px;
    background: rgba(0, 0, 0, 0.8);
    color: white;
    display: inline;
    position: absolute;
    height: 36px;
    top: 2px;
  }
</style>
