// src/dashboard/host-panel/main.vue
<template>
  <v-app>
    <v-container fluid>
      <div id="host-container">
        <div>
          <reader-bid-prize-panel
            class="panel"
            :item="shownItemOnPanel"
            v-if="showBidPrizePanel"
          />
        </div>
        <div>
          <host-panel-countdown
            class="panel"
            :hostCountdownReplicant="hostCountdownReplicant"
          />
        </div>

        <div class="break"></div>

        <div id="left" class="column">
          <reader-panel-bids class="panel" :bids="allBids" />
        </div>
        <div id="right" class="column">
          <reader-panel-total class="panel" :total="total" />
          <reader-panel-milestones
            class="panel"
            :milestones="milestones"
            :total="total"
          />
          <v-btn @click="switchToIntermission"
            >Awaryjny przycisk zmiany na przerwę</v-btn
          >
        </div>
      </div>
    </v-container>
  </v-app>
</template>

<script lang="ts">
  import { Vue, Component, Watch } from 'vue-property-decorator';
  import type { Bids, Total } from '@gsps-layouts/types/schemas';
  import type { Countdown } from '@gsps-layouts/types/schemas/countdown';
  import { Bid, Milestones, Prize } from '@gsps-layouts/types';
  import { Getter } from 'vuex-class';
  import ReaderPanelTotal from './components/Total.vue';
  import ReaderPanelBids from './components/Bids.vue';
  import ReaderPanelMilestones from './components/Milestones.vue';
  import HostPanelCountdown from './components/Countdown.vue';
  import ReaderBidPrizePanel from './components/BidPrizePanel.vue';

  @Component({
    components: {
      ReaderPanelTotal,
      ReaderPanelBids,
      ReaderPanelMilestones,
      HostPanelCountdown,
      ReaderBidPrizePanel,
    },
  })
  export default class extends Vue {
    @Getter readonly allBids!: Bids[];
    @Getter readonly total!: Total;
    @Getter readonly milestones!: Milestones;
    @Getter readonly hostCountdownReplicant!: Countdown;
    @Getter readonly currentBid!: Bid;
    @Getter readonly currentPrize!: Prize;
    @Getter readonly showBidsPanel!: boolean;
    @Getter readonly showPrizePanel!: boolean;

    shownItemOnPanel: Bid | Prize | null = null;
    showBidPrizePanel = false;

    @Watch('currentBid')
    onCurrentBidChange(bid: Bid | null) {
      this.shownItemOnPanel = bid;
    }

    @Watch('currentPrize')
    onCurrentPrizeChange(prize: Prize | null) {
      this.shownItemOnPanel = prize;
    }

    @Watch('showBidsPanel')
    onShowBidsPanelChange(value: boolean) {
      console.log(value);
      if (!value && !this.showPrizePanel) {
        this.showBidPrizePanel = false;
      } else {
        this.showBidPrizePanel = true;
      }
    }

    @Watch('showPrizePanel')
    onShowPrizePanelChange(value: boolean) {
      if (!value && !this.showBidsPanel) {
        this.showBidPrizePanel = false;
      } else {
        this.showBidPrizePanel = true;
      }
    }

    switchToIntermission(): void {
      nodecg.sendMessage('switchFromHostScreen');
    }
  }
</script>

<style>
  #host-container {
    display: flex;
    flex-flow: row wrap;
    width: 100%;
    height: 100%;
    justify-content: center;
    padding: 5px;
  }

  .panel {
    margin: 5px;
  }

  .column {
    flex-direction: column;
  }

  .break {
    flex-basis: 100%;
    height: 0;
  }
</style>

// src/browser/dashboard/host-panel.tsx
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { render } from '../render';
import { Button, Container, Paper, Stack } from '@mui/material';
import { Bids, Milestones, Total } from './reader-panel';
import { useEffect, useState } from 'react';
import { useReplicant } from 'use-nodecg';
import { Bid, Prize } from 'src/types/custom';
import { Countdown as CountdownType } from 'src/types/generated';

export const BidPrizePanel = () => {
  const [currentBid] = useReplicant<Bid | null>('currentlyShownBid', null);
  const [currentPrize] = useReplicant<Prize | null>('currentlyShownPrize', null);
  const [shownItemOnPanel, setShownItemOnPanel] = useState<{
    type: 'bid' | 'prize';
    data: Bid | Prize;
  } | null>(null);
  const [showPrizePanel] = useReplicant<boolean>('showPrizePanel', false);
  const [showBidPanel] = useReplicant<boolean>('showBidsPanel', false);

  useEffect(() => {
    if (!currentBid) return;
    if (!showBidPanel) return;

    setShownItemOnPanel({ type: 'bid', data: currentBid });
  }, [currentBid, showBidPanel]);

  useEffect(() => {
    if (!currentPrize) return;
    if (!showPrizePanel) return;

    setShownItemOnPanel({ type: 'prize', data: currentPrize });
  }, [currentPrize, showPrizePanel]);

  return (
    <>
      {(showBidPanel || showPrizePanel) && (
        <Paper
          sx={{
            width: '500px',
            height: '100px',
            display: 'flex',
            flexDirection: 'column',
            padding: '5px',
          }}>
          <h3
            style={{
              width: '100%',
              textAlign: 'center',
              color: 'white',
              marginTop: '10px',
            }}>
            {shownItemOnPanel ? (
              <>
                {shownItemOnPanel.type == 'bid' ? (
                  <>OBECNIE POKAZYWANA LICYTACJA</>
                ) : (
                  <>OBECNIE POKAZYWANA NAGRODA</>
                )}
              </>
            ) : (
              <>OBECNIE POKAZYWANA NAGRODA/LICYTACJA</>
            )}
          </h3>
          <div id="data" style={{ margin: 3, textAlign: 'center' }}>
            <b style={{ fontSize: '20px' }}>
              {shownItemOnPanel && (
                <>
                  {shownItemOnPanel.type === 'bid' ? (
                    <>
                      {(shownItemOnPanel.data as Bid).game} -
                      {(shownItemOnPanel.data as Bid).description}
                    </>
                  ) : (
                    <>{(shownItemOnPanel.data as Prize).name}</>
                  )}
                </>
              )}
            </b>
          </div>
        </Paper>
      )}
    </>
  );
};

const Countdown = () => {
  const [hostCountdown] = useReplicant<CountdownType | undefined>('hostCountdown', undefined);
  const [hostCountdownRunning] = useReplicant<boolean>('hostCountdownRunning', false);

  function countdownStyles() {
    const underLimitColor = '#357C3C';
    const warningColor = '#FFC300';
    const overLimitColor = '#FF5959';
    const warningSeconds = 30;
    const msInSecond = 1000;
    const baseFontSize = 48;
    const maxFontSize = 380;

    const secondsLeft = hostCountdown!.raw / msInSecond;

    let fontSize = baseFontSize;
    let color = underLimitColor;
    if (secondsLeft <= 0) {
      color = overLimitColor;
      fontSize = Math.min(baseFontSize + -secondsLeft * 2, maxFontSize);
    } else if (secondsLeft <= warningSeconds) {
      color = warningColor;
    }

    return { color: color, fontSize: `${fontSize}px` };
  }

  return (
    <>
      {hostCountdown && hostCountdownRunning && (
        <Paper sx={{ minWidth: '450px', textAlign: 'center' }}>
          <Stack spacing={0}>
            <h3
              style={{
                width: '100%',
                textAlign: 'center',
                color: 'white',
                marginTop: '10px',
              }}>
              POZOSTAŁY CZAS
            </h3>
            <b>
              <span style={countdownStyles()}>{hostCountdown.formatted}</span>
            </b>
          </Stack>
        </Paper>
      )}
    </>
  );
};

const HostPanel = () => {
  return (
    <DashboardThemeProvider>
      <Container disableGutters>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '25px' }}>
          <div
            style={{ display: 'flex', flexDirection: 'column', gap: '25px', alignItems: 'center' }}>
            <BidPrizePanel />
            <Countdown />
          </div>
          <div
            style={{
              display: 'flex',
              flexDirection: 'row',
              width: '100%',
              height: '100%',
              justifyContent: 'center',
              padding: '5px',
              gap: '15px',
            }}>
            <div id="left" style={{ display: 'flex', gap: '10px', flexDirection: 'column' }}>
              <Bids />
            </div>
            <div id="right" style={{ display: 'flex', gap: '10px', flexDirection: 'column' }}>
              <Total />
              <Milestones />
              <Button
                variant="contained"
                onClick={() => {
                  nodecg.sendMessage('switchFromHostScreen');
                }}>
                Awaryjny przycisk zmiany na przerwę
              </Button>
            </div>
          </div>
        </div>
      </Container>
    </DashboardThemeProvider>
  );
};

render(<HostPanel />);
