// src/dashboard/play-video/main.vue
<template>
  <v-app>
    <v-row no-gutters>
      <v-btn
        :disabled="obsData.scene != sceneName"
        @click="playShortIntermissionVideo"
        ><v-icon left>mdi-play</v-icon>Krótki film na przerwie</v-btn
      >
      <v-btn
        :disabled="obsData.scene != sceneName"
        @click="playLongIntermissionVideo"
        class="ml-6"
        ><v-icon left>mdi-play</v-icon>Długi (ok. 5min) film na przerwie</v-btn
      >
    </v-row>
  </v-app>
</template>

<script lang="ts">
  import { Vue, Component } from 'vue-property-decorator';
  import type { ObsData, Configschema } from '@gsps-layouts/types/schemas';
  import { Getter } from 'vuex-class';

  @Component
  export default class extends Vue {
    @Getter readonly obsData!: ObsData;

    config = (nodecg.bundleConfig as Configschema).obs;

    sceneName: string = this.config.scenes!.intermission;

    playShortIntermissionVideo() {
      nodecg.sendMessage('playIntermissionVideo', false);
    }

    playLongIntermissionVideo() {
      nodecg.sendMessage('playIntermissionVideo', true);
    }
  }
</script>

<style>
  body {
    text-align: center;
  }
</style>

// src/browser/dashboard/play-video.tsx
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { render } from '../render';
import { useReplicant } from 'use-nodecg';
import { Button, Stack } from '@mui/material';
import { ObsData } from 'src/types/generated';

const intermissionSceneName = nodecg.bundleConfig.obs.scenes?.intermission;

export const App = () => {
  const [obsData] = useReplicant<ObsData | undefined>('obsData', undefined);
  return (
    <DashboardThemeProvider>
      {obsData && (
        <Stack spacing={1} useFlexGap>
          <Button
            variant="contained"
            disabled={obsData.scene != intermissionSceneName}
            onClick={() => {
              nodecg.sendMessage('playIntermissionVideo', false);
            }}>
            Krótki film na przerwie
          </Button>
          <Button
            variant="contained"
            disabled={obsData.scene != intermissionSceneName}
            onClick={() => {
              nodecg.sendMessage('playIntermissionVideo', true);
            }}>
            Długi (ok. 5min) film na przerwie
          </Button>
        </Stack>
      )}
    </DashboardThemeProvider>
  );
};

render(<App />);
