// src/dashboard/total/main.vue
<template>
    <v-app>
        <v-tooltip bottom>
            <template v-slot:activator="{ on, attrs }">
                <v-card nodecg-dialog="edit-total" v-bind="attrs" v-on="on">
                    <v-card-subtitle id="amount">
                        <h1>{{ totalReplicant.formatted }}</h1>
                    </v-card-subtitle>
                </v-card>
            </template>
            <span>Naciśnij, aby edytować kwotę</span>
        </v-tooltip>
        <br />
        <v-btn
            v-on:click="
                () => {
                    updateTotal()
                }
            "
            >Zaktualizuj kwotę ręcznie</v-btn
        >
        <v-switch
            v-model="autoUpdateTotal"
            v-on:change="
                () => {
                    updateAutoUpdate()
                }
            "
            label="Aktualizuj kwotę automatycznie"
        ></v-switch>
    </v-app>
</template>

<script lang="ts">
    import { Vue, Component } from 'vue-property-decorator'
    import type { AutoUpdateTotal, Total } from '@gsps-layouts/types/schemas'
    import { Getter } from 'vuex-class'
    import { storeModule } from './store'

    @Component
    export default class extends Vue {
        data() {
            return {
                autoUpdateTotal: false,
            }
        }
        @Getter readonly totalReplicant!: Total
        @Getter readonly autoUpdateTotalReplicant!: AutoUpdateTotal

        autoUpdateTotal = this.autoUpdateTotalReplicant

        updateTotal(): void {
            nodecg.sendMessage('updateTotal')
        }

        updateAutoUpdate(): void {
            storeModule.updateAutoUpdateReplicant(this.autoUpdateTotal)
        }

        mounted() {
            this.$data.autoUpdateTotal = this.autoUpdateTotalReplicant
        }
    }
</script>

<style>
    #amount {
        text-align: center;
        color: white;
    }

    body {
        text-align: center;
    }
</style>

// src/browser/dashboard/total.tsx
import { useReplicant } from 'use-nodecg';
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { render } from '../render';
import {
  Tooltip,
  Button,
  Paper,
  Typography,
  FormGroup,
  FormControlLabel,
  Switch,
  Container,
  Stack,
} from '@mui/material';
import { AutoUpdateTotal, Total } from 'src/types/generated';

export const App = () => {
  const [total] = useReplicant<Total | undefined>('total', undefined);
  const [autoUpdateTotal, setAutoUpdateTotal] = useReplicant<AutoUpdateTotal>(
    'autoUpdateTotal',
    false
  );

  return (
    <DashboardThemeProvider>
      <Container>
        <Stack spacing={2}>
          <Tooltip
            title="Naciśnij, aby edytować kwotę"
            onClick={() => {
              nodecg.getDialog('edit-total')!.open();
            }}>
            <Paper style={{ textAlign: 'center' }} variant="outlined" elevation={3}>
              {total && (
                <Typography style={{ margin: '10px' }} variant="h4">
                  <b>{total.formatted}</b>
                </Typography>
              )}
            </Paper>
          </Tooltip>
          <Button
            variant="contained"
            onClick={() => {
              nodecg.sendMessage('updateTotal');
            }}>
            Zaktualizuj kwotę ręcznie
          </Button>
          <FormGroup>
            <FormControlLabel
              control={
                <Switch
                  checked={autoUpdateTotal}
                  onChange={(event) => {
                    setAutoUpdateTotal(event.target.checked);
                  }}
                />
              }
              label="Aktualizuj kwotę automatycznie"
            />
          </FormGroup>
        </Stack>
      </Container>
    </DashboardThemeProvider>
  );
};

render(<App />);
