// src/browser/dashboard/obs-status.tsx
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { render } from '../render';
import { useReplicant } from 'use-nodecg';
import { Typography } from '@mui/material';
import { ObsData } from 'src/types/generated';

export const App = () => {
  const [obsData] = useReplicant<ObsData | undefined>('obsData', undefined);
  return (
    <DashboardThemeProvider>
      {obsData && (
        <div style={{ textAlign: 'center' }}>
          <Typography variant="h5">
            <b>
              {!obsData.connected && <span style={{ color: 'red' }}>NIE </span>}
              <span style={{ color: obsData.connected ? 'green' : 'red' }}>POŁĄCZONO </span>z OBSem
            </b>
          </Typography>
          <Typography variant="h5">
            <b>
              <span>Stream: </span>
              {!obsData.streaming && <span style={{ color: 'red' }}>NIE </span>}
              <span style={{ color: obsData.streaming ? 'green' : 'red' }}>WŁĄCZONY</span>
            </b>
          </Typography>
          <Typography variant="h5">
            <b>
              <span>Nagrywanie: </span>
              {!obsData.recording && <span style={{ color: 'red' }}>NIE </span>}
              <span style={{ color: obsData.recording ? 'green' : 'red' }}>WŁĄCZONE</span>
            </b>
          </Typography>
        </div>
      )}
    </DashboardThemeProvider>
  );
};

render(<App />);

// src/dashboard/obs-status/main.vue
<template>
    <v-app>
        <div id="connected">
            <h2>
                <span v-if="!obsData.connected" style="color: red">NIE </span
                ><span
                    :style="
                        obsData.connected
                            ? { color: 'green' }
                            : { color: 'red' }
                    "
                    >POŁĄCZONO</span
                >
                z OBSem
            </h2>
        </div>
        <div id="stream-record" v-if="obsData.connected">
            <h2>
                <span>Stream: </span
                ><span v-if="!obsData.streaming" style="color: red">NIE </span
                ><span
                    :style="
                        obsData.streaming
                            ? { color: 'green' }
                            : { color: 'red' }
                    "
                    >WŁĄCZONY</span
                >
            </h2>
            <h2>
                <span>Nagrywanie: </span
                ><span v-if="!obsData.recording" style="color: red">NIE </span
                ><span
                    :style="
                        obsData.recording
                            ? { color: 'green' }
                            : { color: 'red' }
                    "
                    >WŁĄCZONE</span
                >
            </h2>
        </div>
    </v-app>
</template>

<script lang="ts">
    import { Vue, Component } from 'vue-property-decorator'
    import type { ObsData } from '@gsps-layouts/types/schemas'
    import { Getter } from 'vuex-class'

    @Component
    export default class extends Vue {
        @Getter readonly obsData!: ObsData
    }
</script>

<style>
    body {
        text-align: center;
    }
</style>
