// src/graphics/_misc/components/Reader.vue
<template>
    <div :style="{ 'display': 'flex', 'flex-direction': 'row', 'color': 'white', 'font-size': '20px', 'width': '100%' }">
        <div :style="{ 'background-color': '#3A008B', 'width': '140px', 'font-size': '18px' }"><b>Czytający</b></div>
        <div :style="{ 'background-color': 'rgb(0,0,0,0.6)', 'width': 'calc(100% - 140px)' }">{{ reader }}</div>
    </div>
</template>

<script>
export default {
    name: 'ReaderName',
    props: ['reader']
}
</script>

// src/browser/graphics/components/reader.tsx
import styled from 'styled-components';
import { useReplicant } from '../../../use-replicant';

const readerRep = nodecg.Replicant('reader');

const ReaderContainer = styled.div`
  display: flex;
  flex-direction: row;
  height: 32.5px;
`;

const ReaderLabel = styled.div`
  background-color: #5f3ac2;
  width: 140px;
  font-size: 18px;
`;

const ReaderName = styled.div`
  background-color: rgba(0, 0, 0, 0.6);
  width: calc(100% - 140px);
  font-size: 20px;
  border-bottom: 2px solid #5f3ac2;
`;

const Pronouns = styled.span`
  font-weight: 400;
  font-size: 0.5em;
  color: #cccccc;
  text-transform: uppercase;
  background-color: #2d1d3c;
  padding: 3px;
  height: 15px;
  margin-left: 8px;
`;

const Reader = () => {
  const [reader] = useReplicant(readerRep);
  return (
    <>
      {reader && (
        <ReaderContainer>
          <ReaderLabel>
            <p style={{ marginTop: '4px' }}>Czytający</p>
          </ReaderLabel>
          <ReaderName>
            <p style={{ marginTop: '3px' }}>
              {reader.name} {reader.pronouns && <Pronouns>{reader.pronouns}</Pronouns>}
            </p>
          </ReaderName>
        </ReaderContainer>
      )}
    </>
  );
};

export default Reader;
