// src/browser/graphics/components/omnibar/ticker.tsx
import styled from 'styled-components';
import GenericMessage from './ticker/generic-message';
import NextRuns from './ticker/next-runs';
import Bids from './ticker/bids';
import Prizes from './ticker/prizes';
//import Milestones from './ticker/milestones';
import { useLayoutEffect, useState } from 'react';

const TickerContainer = styled.div`
  flex: 1;
  display: flex;
  flex-direction: row;
  align-items: center;
`;

const Ticker = () => {
  const [currentElement, setCurrentElement] = useState<React.JSX.Element | undefined>(undefined);
  const [timestamp, setTimestamp] = useState(Date.now());
  let currentComponentIndex = 0;

  function genericMsg(message: string) {
    return <GenericMessage message={message} onEnd={showNextElement} />;
  }

  function gspsPromo() {
    return genericMsg(
      'Oglądacie&nbsp;<b class="highlight">Gramy Szybko, Pomagamy Skutecznie 2024</b>!'
    );
  }

  function charityPromo() {
    return genericMsg(
      'GSPS 2024 wspiera&nbsp;<b class="highlight">Fundację ITAKA</b>!'
    );
  }

  function donationURL() {
    return genericMsg('Wesprzyj na&nbsp;<b class="highlight">gsps.pl/wesprzyj</b>!');
  }

  /*   function gspsAbout() {
    return genericMsg(
      'Więcej o wydarzeniach z serii GSPS możecie się dowiedzieć na <b class="highlight">gsps.pl</b>!'
    );
  } */

  function nextRuns() {
    return <NextRuns onEnd={showNextElement} />;
  }

  function bids() {
    return <Bids onEnd={showNextElement} />;
  }

  function prizes() {
    return <Prizes onEnd={showNextElement} />;
  }

  /* function milestones() {
    return <Milestones onEnd={showNextElement} />;
  } */

  const messageTypes = [
    gspsPromo(),
    charityPromo(),
    donationURL(),
    nextRuns(),
    bids(),
    //prizes(),
    //milestones(),
  ];

  function showNextElement() {
    console.log('SHOWING NEXT MESSAGE');
    currentComponentIndex += 1;
    if (currentComponentIndex >= messageTypes.length) {
      currentComponentIndex = 0;
    }
    setTimestamp(Date.now());
    setCurrentElement(messageTypes[currentComponentIndex]);
  }

  useLayoutEffect(() => {
    // set first element on mount
    setCurrentElement(messageTypes[0]);
  }, []);

  return (
    <TickerContainer>
      <span key={timestamp}>{currentElement}</span>
    </TickerContainer>
  );
};

export default Ticker;

// src/graphics/omnibar/components/Ticker.vue
<template>
  <div id="Ticker">
    <transition name="fade" mode="out-in">
      <component
        :is="currentComponent.name"
        :key="timestamp"
        :data="currentComponent.data"
        @end="showNextMsg"
      />
    </transition>
  </div>
</template>

<script>
  import TickerGenericMessage from './Ticker/GenericMessage.vue';
  import TickerBidGoal from './Ticker/BidGoal.vue';
  import TickerBidWar from './Ticker/BidWar.vue';
  import TickerNextRuns from './Ticker/NextRuns.vue';
  import TickerMilestone from './Ticker/Milestone.vue';
  import TickerPrizes from './Ticker/Prizes.vue';
  const bids = nodecg.Replicant('currentBids');
  const runs = nodecg.Replicant('runDataArray', 'nodecg-speedcontrol');
  const activeRun = nodecg.Replicant('runDataActiveRun', 'nodecg-speedcontrol');
  const milestones = nodecg.Replicant('milestones');
  const total = nodecg.Replicant('total');
  const prizes = nodecg.Replicant('prizes');

  export default {
    name: 'OmnibarTicker',
    data() {
      return {
        currentComponent: {
          name: '',
          data: {},
        },
        currentComponentIndex: 0,
        timestamp: Date.now(),
        messageTypes: [],
      };
    },
    mounted() {
      NodeCG.waitForReplicants(
        bids,
        runs,
        activeRun,
        milestones,
        total,
        prizes
      ).then(() => {
        this.messageTypes = [
          this.gspsPromo(),
          this.charityPromo(),
          this.donationURL(),
          this.nextRuns(),
          this.bidGoal(),
          this.bidWar(),
          this.milestone(),
          this.prizes(),
        ];

        this.currentComponent = this.messageTypes[0];
      });
    },
    methods: {
      showNextMsg() {
        console.log('SHOWING NEXT MESSAGE');
        this.currentComponentIndex += 1;
        if (this.currentComponentIndex >= this.messageTypes.length) {
          this.currentComponentIndex = 0;
        }
        this.currentComponent = this.messageTypes[this.currentComponentIndex];
        this.timestamp = Date.now();
      },

      gspsPromo() {
        return this.genericMsg(
          'Oglądacie&nbsp;<b style="color: #ffbd16">Gramy Szybko, Pomagamy Skutecznie Dzieciom 2023</b>!'
        );
      },

      charityPromo() {
        return this.genericMsg(
          '<b>GSPS Dzieciom 2023</b>&nbsp;wspiera&nbsp;<b style="color: #ffbd16">Fundację Na Ratunek Dzieciom z Chorobą Nowotworową</b>!'
        );
      },

      donationURL() {
        return this.genericMsg(
          'Wesprzyj na&nbsp;<b style="color: #ffbd16">gsps.pl/wesprzyj</b>!'
        );
      },

      genericMsg(string) {
        return {
          name: TickerGenericMessage,
          data: {
            msg: string,
          },
        };
      },

      bidGoal() {
        return {
          name: TickerBidGoal,
        };
      },

      bidWar() {
        return {
          name: TickerBidWar,
        };
      },

      nextRuns() {
        return {
          name: TickerNextRuns,
        };
      },

      milestone() {
        return {
          name: TickerMilestone,
        };
      },

      prizes() {
        return {
          name: TickerPrizes,
        };
      },
    },
  };
</script>

<style scoped>
  #Ticker {
    height: 100%;
    min-width: 0;
    flex: 1;
  }

  .fade-enter-active,
  .fade-leave-active {
    transition: opacity 0.5s;
  }
  .fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
    opacity: 0;
  }
</style>
