// src/browser/dashboard/secondary-timer.tsx
import { useReplicant } from 'use-nodecg';
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { render } from '../render';
import { Button, FormControlLabel, FormGroup, Grid, Switch, Typography } from '@mui/material';
import { SecondaryTimer } from 'src/types/generated';

export const App = () => {
  const [timer, setTimer] = useReplicant<SecondaryTimer | undefined>('secondaryTimer', undefined);

  return (
    <DashboardThemeProvider>
      <div style={{ textAlign: 'center' }}>
        {timer && (
          <>
            {' '}
            <FormGroup>
              <FormControlLabel
                control={
                  <Switch
                    checked={timer.enabled}
                    onChange={(event) => {
                      const newVal = { ...timer };
                      newVal.enabled = event.target.checked;
                      setTimer(newVal);
                    }}
                  />
                }
                label="Włącz dodatkowy timer"
              />
            </FormGroup>
            <Typography variant="h3" gutterBottom>
              <b>{timer.time}</b>
            </Typography>
            <Grid style={{ width: '100%' }} container spacing={0} justifyContent="space-between">
              <Grid item xs={0}>
                <Button
                  variant="contained"
                  onClick={() => {
                    if (timer.phase == 'stopped' || timer.phase == 'paused') {
                      nodecg.sendMessage('secondaryTimerStart');
                    } else if (timer.phase == 'running') {
                      nodecg.sendMessage('secondaryTimerFinish');
                    }
                  }}
                  disabled={timer.phase === 'finished'}>
                  {timer.phase === 'running' ? 'Zakończ timer' : 'Rozpocznij timer'}
                </Button>
              </Grid>
              <Grid item xs={0}>
                <Button
                  variant="contained"
                  onClick={() => {
                    nodecg.sendMessage('secondaryTimerReset', true);
                  }}
                  disabled={timer.phase === 'stopped'}>
                  Resetuj timer
                </Button>
              </Grid>
            </Grid>
          </>
        )}
      </div>
    </DashboardThemeProvider>
  );
};

render(<App />);

// src/dashboard/secondary-timer/main.vue
<template>
  <v-app>
    <v-container flud class="text-center">
      <v-switch
        v-model="timerEnabled"
        @change="
          () => {
            updateTimerEnabledState();
          }
        "
        label="Włącz dodatkowy timer"
      />
    </v-container>
    <v-container fluid class="text-center">
      <h1 style="font-size: 48px">{{ timer.time }}</h1>
    </v-container>
    <v-container
      fluid
      class="d-flex text-center"
      style="justify-content: space-between"
    >
      <v-btn width="45%" @click="startTimer" :disabled="phase === 'finished'">{{
        phase === 'running' ? 'Zakończ Timer' : 'Wystartuj Timer'
      }}</v-btn>
      <v-btn width="45%" @click="resetTimer" :disabled="phase === 'stopped'"
        >Zresetuj Timer</v-btn
      >
    </v-container>
  </v-app>
</template>

<script lang="ts">
  import { Vue, Component } from 'vue-property-decorator';
  import type { SecondaryTimer } from '@gsps-layouts/types/schemas';
  import { Getter } from 'vuex-class';
  import { storeModule } from './store';

  @Component
  export default class extends Vue {
    @Getter readonly timer!: SecondaryTimer; // from store.ts

    timerEnabled = this.timer.enabled;

    get phase() {
      return this.timer.phase;
    }

    async startTimer(): Promise<void> {
      try {
        if (this.phase === 'stopped' || this.phase === 'paused') {
          await nodecg.sendMessage('secondaryTimerStart');
        } else if (this.phase === 'running') {
          await nodecg.sendMessage('secondaryTimerFinish');
        }
      } catch (err) {
        // catch
      }
    }

    async resetTimer(): Promise<void> {
      try {
        await nodecg.sendMessage('secondaryTimerReset', true);
      } catch (err) {
        // error
      }
    }
    updateTimerEnabledState() {
      storeModule.updateTimerEnabledState(this.timerEnabled);
    }

    mounted() {
      this.$data.timerEnabled = this.timer.enabled;
    }
  }
</script>
