// src/browser/graphics/components/omnibar/total.tsx
import styled from 'styled-components';
import { useEffect, useState } from 'react';
import { Total as TotalType } from 'src/types/generated';
import gsap from 'gsap';

const AmountDiv = styled.div`
  font-size: 34px;
  align-self: flex-end;
  padding-left: 10px;
  padding-right: 10px;
  margin-top: auto;
  margin-bottom: auto;
  text-align: right;
  font-variant-numeric: tabular-nums;
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 10px;
`;

const Currency = styled.div`
  font-size: 0.7em;
`;

export const Total = () => {
  const totalRep = nodecg.Replicant<TotalType>('total');
  const [amount, setAmount] = useState({ raw: 0, formatted: '0' });
  const localAmount = { raw: 0 };

  useEffect(() => {
    const ctx = gsap.context(() => {
      totalRep.on('change', (newVal: any) => {
        if (typeof newVal != 'undefined') {
          gsap.to(localAmount, {
            duration: 5,
            raw: newVal.raw,
            roundProps: 'raw',
            ease: 'power4',
            onUpdate: () => {
              setAmount({
                raw: localAmount.raw,
                formatted: localAmount.raw.toLocaleString('en-US', {
                  maximumFractionDigits: 0,
                  minimumFractionDigits: 0,
                }),
              });
            },
          });
        }
      });
    });

    return () => ctx.revert();
  }, []);

  return (
    <AmountDiv>
      {amount.formatted}
      <Currency>PLN</Currency>
    </AmountDiv>
  );
};

export default Total;

// src/graphics/break/components/Total.vue
<template>
    <div id="total">
        <div id="totalAmount"></div>
        <div id="totalCurrency">PLN</div>
    </div>
</template>

<script lang="ts">
    import type { Total } from '../../../types/schemas'
    import gsap from 'gsap'
    import { Component, Vue } from 'vue-property-decorator'

    const totalRep = nodecg.Replicant<Total>('total')

    @Component
    export default class BreakTotal extends Vue {
        data() {
            return {
                total: { raw: 0 },
            }
        }

        mounted() {
            const updateHandler = () => {
                document.getElementById('totalAmount')!.innerHTML =
                    this.$data.total.raw.toLocaleString('en-US', {
                        maximumFractionDigits: 0,
                        minimumFractionDigits: 0,
                    })
            }
            totalRep.on('change', (newVal) => {
                gsap.to(this.$data.total, {
                    duration: 3,
                    raw: newVal.raw,
                    roundProps: 'raw',
                    onUpdate: updateHandler,
                    ease: 'power4',
                })
            })
        }
    }
</script>

<style scoped>
    #total {
        color: white;
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 100px;
    }

    #totalAmount {
        font-weight: bold;
    }

    #totalCurrency {
        font-size: 64px;
        margin-left: 20px;
    }
</style>
